// flow-typed signature: 000cb4094204269380076d579ce0b34e
// flow-typed version: <<STUB>>/mongoose_v^4.10.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongoose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mongoose/examples/aggregate/aggregate' {
  declare module.exports: any;
}

declare module 'mongoose/examples/aggregate/person' {
  declare module.exports: any;
}

declare module 'mongoose/examples/doc-methods' {
  declare module.exports: any;
}

declare module 'mongoose/examples/express/connection-sharing/app' {
  declare module.exports: any;
}

declare module 'mongoose/examples/express/connection-sharing/modelA' {
  declare module.exports: any;
}

declare module 'mongoose/examples/express/connection-sharing/routes' {
  declare module.exports: any;
}

declare module 'mongoose/examples/geospatial/geoJSONexample' {
  declare module.exports: any;
}

declare module 'mongoose/examples/geospatial/geoJSONSchema' {
  declare module.exports: any;
}

declare module 'mongoose/examples/geospatial/geospatial' {
  declare module.exports: any;
}

declare module 'mongoose/examples/geospatial/person' {
  declare module.exports: any;
}

declare module 'mongoose/examples/globalschemas/gs_example' {
  declare module.exports: any;
}

declare module 'mongoose/examples/globalschemas/person' {
  declare module.exports: any;
}

declare module 'mongoose/examples/lean/lean' {
  declare module.exports: any;
}

declare module 'mongoose/examples/lean/person' {
  declare module.exports: any;
}

declare module 'mongoose/examples/mapreduce/mapreduce' {
  declare module.exports: any;
}

declare module 'mongoose/examples/mapreduce/person' {
  declare module.exports: any;
}

declare module 'mongoose/examples/population/population-across-three-collections' {
  declare module.exports: any;
}

declare module 'mongoose/examples/population/population-basic' {
  declare module.exports: any;
}

declare module 'mongoose/examples/population/population-of-existing-doc' {
  declare module.exports: any;
}

declare module 'mongoose/examples/population/population-of-multiple-existing-docs' {
  declare module.exports: any;
}

declare module 'mongoose/examples/population/population-options' {
  declare module.exports: any;
}

declare module 'mongoose/examples/population/population-plain-objects' {
  declare module.exports: any;
}

declare module 'mongoose/examples/promises/person' {
  declare module.exports: any;
}

declare module 'mongoose/examples/promises/promise' {
  declare module.exports: any;
}

declare module 'mongoose/examples/querybuilder/person' {
  declare module.exports: any;
}

declare module 'mongoose/examples/querybuilder/querybuilder' {
  declare module.exports: any;
}

declare module 'mongoose/examples/replicasets/person' {
  declare module.exports: any;
}

declare module 'mongoose/examples/replicasets/replica-sets' {
  declare module.exports: any;
}

declare module 'mongoose/examples/schema/schema' {
  declare module.exports: any;
}

declare module 'mongoose/examples/schema/storing-schemas-as-json/index' {
  declare module.exports: any;
}

declare module 'mongoose/examples/statics/person' {
  declare module.exports: any;
}

declare module 'mongoose/examples/statics/statics' {
  declare module.exports: any;
}

declare module 'mongoose/lib/aggregate' {
  declare module.exports: any;
}

declare module 'mongoose/lib/browser' {
  declare module.exports: any;
}

declare module 'mongoose/lib/browserDocument' {
  declare module.exports: any;
}

declare module 'mongoose/lib/cast' {
  declare module.exports: any;
}

declare module 'mongoose/lib/collection' {
  declare module.exports: any;
}

declare module 'mongoose/lib/connection' {
  declare module.exports: any;
}

declare module 'mongoose/lib/connectionstate' {
  declare module.exports: any;
}

declare module 'mongoose/lib/cursor/AggregationCursor' {
  declare module.exports: any;
}

declare module 'mongoose/lib/document_provider' {
  declare module.exports: any;
}

declare module 'mongoose/lib/document_provider.web' {
  declare module.exports: any;
}

declare module 'mongoose/lib/document' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/browser/binary' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/browser/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/browser/objectid' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/browser/ReadPreference' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/index.web' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/binary' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/collection' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/connection' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/objectid' {
  declare module.exports: any;
}

declare module 'mongoose/lib/drivers/node-mongodb-native/ReadPreference' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/browserMissingSchema' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/cast' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/disconnected' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/divergentArray' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/messages' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/missingSchema' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/notFound' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/objectExpected' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/overwriteModel' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/strict' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/validation' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/validator' {
  declare module.exports: any;
}

declare module 'mongoose/lib/error/version' {
  declare module.exports: any;
}

declare module 'mongoose/lib/ES6Promise' {
  declare module.exports: any;
}

declare module 'mongoose/lib/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/internal' {
  declare module.exports: any;
}

declare module 'mongoose/lib/model' {
  declare module.exports: any;
}

declare module 'mongoose/lib/plugins/saveSubdocs' {
  declare module.exports: any;
}

declare module 'mongoose/lib/plugins/sharding' {
  declare module.exports: any;
}

declare module 'mongoose/lib/plugins/validateBeforeSave' {
  declare module.exports: any;
}

declare module 'mongoose/lib/promise_provider' {
  declare module.exports: any;
}

declare module 'mongoose/lib/promise' {
  declare module.exports: any;
}

declare module 'mongoose/lib/query' {
  declare module.exports: any;
}

declare module 'mongoose/lib/querycursor' {
  declare module.exports: any;
}

declare module 'mongoose/lib/queryhelpers' {
  declare module.exports: any;
}

declare module 'mongoose/lib/querystream' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/array' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/boolean' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/buffer' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/date' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/decimal128' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/documentarray' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/embedded' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/mixed' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/number' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/objectid' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/operators/bitwise' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/operators/exists' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/operators/geospatial' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/operators/helpers' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/operators/type' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schema/string' {
  declare module.exports: any;
}

declare module 'mongoose/lib/schematype' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/common' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/model/applyHooks' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/model/applyMethods' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/model/applyStatics' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/model/discriminator' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/projection/isPathSelectedInclusive' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/query/castUpdate' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/query/hasDollarKeys' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/setDefaultsOnInsert' {
  declare module.exports: any;
}

declare module 'mongoose/lib/services/updateValidators' {
  declare module.exports: any;
}

declare module 'mongoose/lib/statemachine' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/array' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/buffer' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/decimal128' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/documentarray' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/embedded' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/index' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/objectid' {
  declare module.exports: any;
}

declare module 'mongoose/lib/types/subdocument' {
  declare module.exports: any;
}

declare module 'mongoose/lib/utils' {
  declare module.exports: any;
}

declare module 'mongoose/lib/virtualtype' {
  declare module.exports: any;
}

declare module 'mongoose/static' {
  declare module.exports: any;
}

declare module 'mongoose/tools/repl' {
  declare module.exports: any;
}

declare module 'mongoose/tools/sharded' {
  declare module.exports: any;
}

declare module 'mongoose/website' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mongoose/examples/aggregate/aggregate.js' {
  declare module.exports: $Exports<'mongoose/examples/aggregate/aggregate'>;
}
declare module 'mongoose/examples/aggregate/person.js' {
  declare module.exports: $Exports<'mongoose/examples/aggregate/person'>;
}
declare module 'mongoose/examples/doc-methods.js' {
  declare module.exports: $Exports<'mongoose/examples/doc-methods'>;
}
declare module 'mongoose/examples/express/connection-sharing/app.js' {
  declare module.exports: $Exports<'mongoose/examples/express/connection-sharing/app'>;
}
declare module 'mongoose/examples/express/connection-sharing/modelA.js' {
  declare module.exports: $Exports<'mongoose/examples/express/connection-sharing/modelA'>;
}
declare module 'mongoose/examples/express/connection-sharing/routes.js' {
  declare module.exports: $Exports<'mongoose/examples/express/connection-sharing/routes'>;
}
declare module 'mongoose/examples/geospatial/geoJSONexample.js' {
  declare module.exports: $Exports<'mongoose/examples/geospatial/geoJSONexample'>;
}
declare module 'mongoose/examples/geospatial/geoJSONSchema.js' {
  declare module.exports: $Exports<'mongoose/examples/geospatial/geoJSONSchema'>;
}
declare module 'mongoose/examples/geospatial/geospatial.js' {
  declare module.exports: $Exports<'mongoose/examples/geospatial/geospatial'>;
}
declare module 'mongoose/examples/geospatial/person.js' {
  declare module.exports: $Exports<'mongoose/examples/geospatial/person'>;
}
declare module 'mongoose/examples/globalschemas/gs_example.js' {
  declare module.exports: $Exports<'mongoose/examples/globalschemas/gs_example'>;
}
declare module 'mongoose/examples/globalschemas/person.js' {
  declare module.exports: $Exports<'mongoose/examples/globalschemas/person'>;
}
declare module 'mongoose/examples/lean/lean.js' {
  declare module.exports: $Exports<'mongoose/examples/lean/lean'>;
}
declare module 'mongoose/examples/lean/person.js' {
  declare module.exports: $Exports<'mongoose/examples/lean/person'>;
}
declare module 'mongoose/examples/mapreduce/mapreduce.js' {
  declare module.exports: $Exports<'mongoose/examples/mapreduce/mapreduce'>;
}
declare module 'mongoose/examples/mapreduce/person.js' {
  declare module.exports: $Exports<'mongoose/examples/mapreduce/person'>;
}
declare module 'mongoose/examples/population/population-across-three-collections.js' {
  declare module.exports: $Exports<'mongoose/examples/population/population-across-three-collections'>;
}
declare module 'mongoose/examples/population/population-basic.js' {
  declare module.exports: $Exports<'mongoose/examples/population/population-basic'>;
}
declare module 'mongoose/examples/population/population-of-existing-doc.js' {
  declare module.exports: $Exports<'mongoose/examples/population/population-of-existing-doc'>;
}
declare module 'mongoose/examples/population/population-of-multiple-existing-docs.js' {
  declare module.exports: $Exports<'mongoose/examples/population/population-of-multiple-existing-docs'>;
}
declare module 'mongoose/examples/population/population-options.js' {
  declare module.exports: $Exports<'mongoose/examples/population/population-options'>;
}
declare module 'mongoose/examples/population/population-plain-objects.js' {
  declare module.exports: $Exports<'mongoose/examples/population/population-plain-objects'>;
}
declare module 'mongoose/examples/promises/person.js' {
  declare module.exports: $Exports<'mongoose/examples/promises/person'>;
}
declare module 'mongoose/examples/promises/promise.js' {
  declare module.exports: $Exports<'mongoose/examples/promises/promise'>;
}
declare module 'mongoose/examples/querybuilder/person.js' {
  declare module.exports: $Exports<'mongoose/examples/querybuilder/person'>;
}
declare module 'mongoose/examples/querybuilder/querybuilder.js' {
  declare module.exports: $Exports<'mongoose/examples/querybuilder/querybuilder'>;
}
declare module 'mongoose/examples/replicasets/person.js' {
  declare module.exports: $Exports<'mongoose/examples/replicasets/person'>;
}
declare module 'mongoose/examples/replicasets/replica-sets.js' {
  declare module.exports: $Exports<'mongoose/examples/replicasets/replica-sets'>;
}
declare module 'mongoose/examples/schema/schema.js' {
  declare module.exports: $Exports<'mongoose/examples/schema/schema'>;
}
declare module 'mongoose/examples/schema/storing-schemas-as-json/index.js' {
  declare module.exports: $Exports<'mongoose/examples/schema/storing-schemas-as-json/index'>;
}
declare module 'mongoose/examples/statics/person.js' {
  declare module.exports: $Exports<'mongoose/examples/statics/person'>;
}
declare module 'mongoose/examples/statics/statics.js' {
  declare module.exports: $Exports<'mongoose/examples/statics/statics'>;
}
declare module 'mongoose/index' {
  declare module.exports: $Exports<'mongoose'>;
}
declare module 'mongoose/index.js' {
  declare module.exports: $Exports<'mongoose'>;
}
declare module 'mongoose/lib/aggregate.js' {
  declare module.exports: $Exports<'mongoose/lib/aggregate'>;
}
declare module 'mongoose/lib/browser.js' {
  declare module.exports: $Exports<'mongoose/lib/browser'>;
}
declare module 'mongoose/lib/browserDocument.js' {
  declare module.exports: $Exports<'mongoose/lib/browserDocument'>;
}
declare module 'mongoose/lib/cast.js' {
  declare module.exports: $Exports<'mongoose/lib/cast'>;
}
declare module 'mongoose/lib/collection.js' {
  declare module.exports: $Exports<'mongoose/lib/collection'>;
}
declare module 'mongoose/lib/connection.js' {
  declare module.exports: $Exports<'mongoose/lib/connection'>;
}
declare module 'mongoose/lib/connectionstate.js' {
  declare module.exports: $Exports<'mongoose/lib/connectionstate'>;
}
declare module 'mongoose/lib/cursor/AggregationCursor.js' {
  declare module.exports: $Exports<'mongoose/lib/cursor/AggregationCursor'>;
}
declare module 'mongoose/lib/document_provider.js' {
  declare module.exports: $Exports<'mongoose/lib/document_provider'>;
}
declare module 'mongoose/lib/document_provider.web.js' {
  declare module.exports: $Exports<'mongoose/lib/document_provider.web'>;
}
declare module 'mongoose/lib/document.js' {
  declare module.exports: $Exports<'mongoose/lib/document'>;
}
declare module 'mongoose/lib/drivers/browser/binary.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/browser/binary'>;
}
declare module 'mongoose/lib/drivers/browser/index.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/browser/index'>;
}
declare module 'mongoose/lib/drivers/browser/objectid.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/browser/objectid'>;
}
declare module 'mongoose/lib/drivers/browser/ReadPreference.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/browser/ReadPreference'>;
}
declare module 'mongoose/lib/drivers/index.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/index'>;
}
declare module 'mongoose/lib/drivers/index.web.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/index.web'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/binary.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/binary'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/collection.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/collection'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/connection.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/connection'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/index.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/index'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/objectid.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/objectid'>;
}
declare module 'mongoose/lib/drivers/node-mongodb-native/ReadPreference.js' {
  declare module.exports: $Exports<'mongoose/lib/drivers/node-mongodb-native/ReadPreference'>;
}
declare module 'mongoose/lib/error.js' {
  declare module.exports: $Exports<'mongoose/lib/error'>;
}
declare module 'mongoose/lib/error/browserMissingSchema.js' {
  declare module.exports: $Exports<'mongoose/lib/error/browserMissingSchema'>;
}
declare module 'mongoose/lib/error/cast.js' {
  declare module.exports: $Exports<'mongoose/lib/error/cast'>;
}
declare module 'mongoose/lib/error/disconnected.js' {
  declare module.exports: $Exports<'mongoose/lib/error/disconnected'>;
}
declare module 'mongoose/lib/error/divergentArray.js' {
  declare module.exports: $Exports<'mongoose/lib/error/divergentArray'>;
}
declare module 'mongoose/lib/error/messages.js' {
  declare module.exports: $Exports<'mongoose/lib/error/messages'>;
}
declare module 'mongoose/lib/error/missingSchema.js' {
  declare module.exports: $Exports<'mongoose/lib/error/missingSchema'>;
}
declare module 'mongoose/lib/error/notFound.js' {
  declare module.exports: $Exports<'mongoose/lib/error/notFound'>;
}
declare module 'mongoose/lib/error/objectExpected.js' {
  declare module.exports: $Exports<'mongoose/lib/error/objectExpected'>;
}
declare module 'mongoose/lib/error/overwriteModel.js' {
  declare module.exports: $Exports<'mongoose/lib/error/overwriteModel'>;
}
declare module 'mongoose/lib/error/strict.js' {
  declare module.exports: $Exports<'mongoose/lib/error/strict'>;
}
declare module 'mongoose/lib/error/validation.js' {
  declare module.exports: $Exports<'mongoose/lib/error/validation'>;
}
declare module 'mongoose/lib/error/validator.js' {
  declare module.exports: $Exports<'mongoose/lib/error/validator'>;
}
declare module 'mongoose/lib/error/version.js' {
  declare module.exports: $Exports<'mongoose/lib/error/version'>;
}
declare module 'mongoose/lib/ES6Promise.js' {
  declare module.exports: $Exports<'mongoose/lib/ES6Promise'>;
}
declare module 'mongoose/lib/index.js' {
  declare module.exports: $Exports<'mongoose/lib/index'>;
}
declare module 'mongoose/lib/internal.js' {
  declare module.exports: $Exports<'mongoose/lib/internal'>;
}
declare module 'mongoose/lib/model.js' {
  declare module.exports: $Exports<'mongoose/lib/model'>;
}
declare module 'mongoose/lib/plugins/saveSubdocs.js' {
  declare module.exports: $Exports<'mongoose/lib/plugins/saveSubdocs'>;
}
declare module 'mongoose/lib/plugins/sharding.js' {
  declare module.exports: $Exports<'mongoose/lib/plugins/sharding'>;
}
declare module 'mongoose/lib/plugins/validateBeforeSave.js' {
  declare module.exports: $Exports<'mongoose/lib/plugins/validateBeforeSave'>;
}
declare module 'mongoose/lib/promise_provider.js' {
  declare module.exports: $Exports<'mongoose/lib/promise_provider'>;
}
declare module 'mongoose/lib/promise.js' {
  declare module.exports: $Exports<'mongoose/lib/promise'>;
}
declare module 'mongoose/lib/query.js' {
  declare module.exports: $Exports<'mongoose/lib/query'>;
}
declare module 'mongoose/lib/querycursor.js' {
  declare module.exports: $Exports<'mongoose/lib/querycursor'>;
}
declare module 'mongoose/lib/queryhelpers.js' {
  declare module.exports: $Exports<'mongoose/lib/queryhelpers'>;
}
declare module 'mongoose/lib/querystream.js' {
  declare module.exports: $Exports<'mongoose/lib/querystream'>;
}
declare module 'mongoose/lib/schema.js' {
  declare module.exports: $Exports<'mongoose/lib/schema'>;
}
declare module 'mongoose/lib/schema/array.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/array'>;
}
declare module 'mongoose/lib/schema/boolean.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/boolean'>;
}
declare module 'mongoose/lib/schema/buffer.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/buffer'>;
}
declare module 'mongoose/lib/schema/date.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/date'>;
}
declare module 'mongoose/lib/schema/decimal128.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/decimal128'>;
}
declare module 'mongoose/lib/schema/documentarray.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/documentarray'>;
}
declare module 'mongoose/lib/schema/embedded.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/embedded'>;
}
declare module 'mongoose/lib/schema/index.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/index'>;
}
declare module 'mongoose/lib/schema/mixed.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/mixed'>;
}
declare module 'mongoose/lib/schema/number.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/number'>;
}
declare module 'mongoose/lib/schema/objectid.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/objectid'>;
}
declare module 'mongoose/lib/schema/operators/bitwise.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/operators/bitwise'>;
}
declare module 'mongoose/lib/schema/operators/exists.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/operators/exists'>;
}
declare module 'mongoose/lib/schema/operators/geospatial.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/operators/geospatial'>;
}
declare module 'mongoose/lib/schema/operators/helpers.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/operators/helpers'>;
}
declare module 'mongoose/lib/schema/operators/type.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/operators/type'>;
}
declare module 'mongoose/lib/schema/string.js' {
  declare module.exports: $Exports<'mongoose/lib/schema/string'>;
}
declare module 'mongoose/lib/schematype.js' {
  declare module.exports: $Exports<'mongoose/lib/schematype'>;
}
declare module 'mongoose/lib/services/common.js' {
  declare module.exports: $Exports<'mongoose/lib/services/common'>;
}
declare module 'mongoose/lib/services/model/applyHooks.js' {
  declare module.exports: $Exports<'mongoose/lib/services/model/applyHooks'>;
}
declare module 'mongoose/lib/services/model/applyMethods.js' {
  declare module.exports: $Exports<'mongoose/lib/services/model/applyMethods'>;
}
declare module 'mongoose/lib/services/model/applyStatics.js' {
  declare module.exports: $Exports<'mongoose/lib/services/model/applyStatics'>;
}
declare module 'mongoose/lib/services/model/discriminator.js' {
  declare module.exports: $Exports<'mongoose/lib/services/model/discriminator'>;
}
declare module 'mongoose/lib/services/projection/isPathSelectedInclusive.js' {
  declare module.exports: $Exports<'mongoose/lib/services/projection/isPathSelectedInclusive'>;
}
declare module 'mongoose/lib/services/query/castUpdate.js' {
  declare module.exports: $Exports<'mongoose/lib/services/query/castUpdate'>;
}
declare module 'mongoose/lib/services/query/hasDollarKeys.js' {
  declare module.exports: $Exports<'mongoose/lib/services/query/hasDollarKeys'>;
}
declare module 'mongoose/lib/services/setDefaultsOnInsert.js' {
  declare module.exports: $Exports<'mongoose/lib/services/setDefaultsOnInsert'>;
}
declare module 'mongoose/lib/services/updateValidators.js' {
  declare module.exports: $Exports<'mongoose/lib/services/updateValidators'>;
}
declare module 'mongoose/lib/statemachine.js' {
  declare module.exports: $Exports<'mongoose/lib/statemachine'>;
}
declare module 'mongoose/lib/types/array.js' {
  declare module.exports: $Exports<'mongoose/lib/types/array'>;
}
declare module 'mongoose/lib/types/buffer.js' {
  declare module.exports: $Exports<'mongoose/lib/types/buffer'>;
}
declare module 'mongoose/lib/types/decimal128.js' {
  declare module.exports: $Exports<'mongoose/lib/types/decimal128'>;
}
declare module 'mongoose/lib/types/documentarray.js' {
  declare module.exports: $Exports<'mongoose/lib/types/documentarray'>;
}
declare module 'mongoose/lib/types/embedded.js' {
  declare module.exports: $Exports<'mongoose/lib/types/embedded'>;
}
declare module 'mongoose/lib/types/index.js' {
  declare module.exports: $Exports<'mongoose/lib/types/index'>;
}
declare module 'mongoose/lib/types/objectid.js' {
  declare module.exports: $Exports<'mongoose/lib/types/objectid'>;
}
declare module 'mongoose/lib/types/subdocument.js' {
  declare module.exports: $Exports<'mongoose/lib/types/subdocument'>;
}
declare module 'mongoose/lib/utils.js' {
  declare module.exports: $Exports<'mongoose/lib/utils'>;
}
declare module 'mongoose/lib/virtualtype.js' {
  declare module.exports: $Exports<'mongoose/lib/virtualtype'>;
}
declare module 'mongoose/static.js' {
  declare module.exports: $Exports<'mongoose/static'>;
}
declare module 'mongoose/tools/repl.js' {
  declare module.exports: $Exports<'mongoose/tools/repl'>;
}
declare module 'mongoose/tools/sharded.js' {
  declare module.exports: $Exports<'mongoose/tools/sharded'>;
}
declare module 'mongoose/website.js' {
  declare module.exports: $Exports<'mongoose/website'>;
}
